[files]
extend-exclude=[
  "experiments/*", 
  "info/*",
  "newpackages/*",
  "*.lvt",
  "*.pvt",
  "*.tlg",
  "*.tpf"
]

[default.extend-words]
Titel   = "Titel"

[default.extend-identifiers]
DecodeParms = "DecodeParms"
Fith  = "Fith"
fith  = "fith"
atend = "atend"
onn   = "onn"
noe   = "noe"
Fo    = "Fo"
nam   = "nam"
Parms  = "Parms"
