rem */\(1+[a-zA-Z0-9\-\_]\)\.\(2+[a-z]\)\.*
rem l3build save -e\2 \1
rem l3build save -cconfig-dvips \1
rem l3build save -cconfig-luatex -e\2 \1
rem l3build save -cconfig-noxetex -e\2 \1

l3build save -eluatex metadata-new-no-hyperref
l3build save -epdftex metadata-new-no-hyperref
l3build save -exetex metadata-new-no-hyperref
l3build save -eluatex metadata-new
l3build save -epdftex metadata-new
l3build save -exetex metadata-new
l3build save -eluatex mixpageattr
l3build save -epdftex mixpageattr
l3build save -exetex mixpageattr
l3build save -eluatex ocgcolorlinks
l3build save -epdftex ocgcolorlinks
l3build save -exetex ocgcolorlinks
l3build save -eluatex ocproperties
l3build save -epdftex ocproperties
l3build save -exetex ocproperties
l3build save -eluatex pageattr
l3build save -epdftex pageattr
l3build save -exetex pageattr
l3build save -eluatex pagelabels
l3build save -epdftex pagelabels
l3build save -exetex pagelabels
l3build save -eluatex pagesattr
l3build save -epdftex pagesattr
l3build save -exetex pagesattr
l3build save -eluatex pdffilelink
l3build save -epdftex pdffilelink
l3build save -exetex pdffilelink
l3build save -eluatex pdflscape
l3build save -epdftex pdflscape
l3build save -exetex pdflscape
l3build save -eluatex pgfpatches
l3build save -epdftex pgfpatches
l3build save -exetex pgfpatches
l3build save -eluatex radiobuttons
l3build save -epdftex radiobuttons
l3build save -exetex radiobuttons
l3build save -eluatex stop-link
l3build save -epdftex stop-link
l3build save -exetex stop-link
l3build save -eluatex tag-checkbox
l3build save -epdftex tag-checkbox
l3build save -exetex tag-checkbox
l3build save -eluatex textfield
l3build save -epdftex textfield
l3build save -exetex textfield
l3build save -eluatex thispageattr
l3build save -epdftex thispageattr
l3build save -exetex thispageattr
l3build save -eluatex transition
l3build save -epdftex transition
l3build save -exetex transition
l3build save -eluatex viewerpreferences
l3build save -epdftex viewerpreferences
l3build save -exetex viewerpreferences
l3build save -eluatex xform-appearance
l3build save -epdftex xform-appearance
l3build save -exetex xform-appearance
l3build save -eluatex xform-preamble
l3build save -epdftex xform-preamble
l3build save -exetex xform-preamble
l3build save -eluatex xform
l3build save -epdftex xform
l3build save -exetex xform
